### ISSUE TITLE
what about "new" type of attacks

### ISSUE THREAD

**Issue by KOLANICH** [NewEraCracker/LOIC#37]
what about "new" type of attacks - slow http connections
content-length header is large
but client sends it terrible slow
server become overloaded with lots of "comet" threads and crashes

**Comment by NewEraCracker** [comment]
1.1.2.x branch is Stale. It won't be released.

There are no plans to add any "new" attacks. LOIC's purpose is to be simple. If you require other functionality, I believe there are better suited tools.

**Comment by NewEraCracker** [comment]
This work is being resumed on:
https://github.com/NewEraCracker/LOIC/tree/BeSquare-tree
It is WORK IN PROGRESS. Expect the unexpected!

**Comment by NewEraCracker** [comment]
BeSquare-tree has been promoted as the new master branch!
https://github.com/NewEraCracker/LOIC/tree/master

Previous 'simple' version is available at:
https://github.com/NewEraCracker/LOIC/tree/stable

**Five years have passed since this issue was first open and the project is now back on track!**
Closing.
